In [1]:
import torch

In [4]:
tmp = [torch.zeros((3,4)) for _ in range(2)]

In [17]:
torch.stack(tmp).view(-1, 3)[:2]

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [2]:
import torch

In [84]:
reps = 1
steps_per_epoch = 3
epochs = 4
alignment_dims = [(reps, steps_per_epoch, 1), (reps, steps_per_epoch, 1),
                  (reps, steps_per_epoch, 5), (reps, steps_per_epoch, 10)]

n_layers = len(alignment_dims)
n_processes = 3
print(f'expected alignment dimensions are: {alignment_dims}')
full_alignment = [[[torch.zeros(layer_dims, dtype=torch.float, device='cpu')
                    for proc in range(n_processes)]
                    for layer_dims in alignment_dims]
                    for step in range(epochs)]

expected alignment dimensions are: [(1, 3, 1), (1, 3, 1), (1, 3, 5), (1, 3, 10)]


In [73]:
for i in range(epochs):
    full_alignment.extend(full_alignment)

In [66]:
cat_processes = [[torch.cat(i_step, axis=1).shape for i_step in layer] for layer in full_alignment]
# print([step for step in cat_processes])

In [85]:
[[torch.cat(i_step, axis=1).shape for i_step in layer] for layer in full_alignment]


[[torch.Size([1, 9, 1]),
  torch.Size([1, 9, 1]),
  torch.Size([1, 9, 5]),
  torch.Size([1, 9, 10])],
 [torch.Size([1, 9, 1]),
  torch.Size([1, 9, 1]),
  torch.Size([1, 9, 5]),
  torch.Size([1, 9, 10])],
 [torch.Size([1, 9, 1]),
  torch.Size([1, 9, 1]),
  torch.Size([1, 9, 5]),
  torch.Size([1, 9, 10])],
 [torch.Size([1, 9, 1]),
  torch.Size([1, 9, 1]),
  torch.Size([1, 9, 5]),
  torch.Size([1, 9, 10])]]

In [87]:
[torch.cat(ilayer, axis=1).shape for ilayer in zip(*cat_processes)]

[torch.Size([1, 36, 1]),
 torch.Size([1, 36, 1]),
 torch.Size([1, 36, 5]),
 torch.Size([1, 36, 10])]

In [125]:
'a' == 'b'

False

In [110]:
tmp2 = [torch.cat(ilayer, axis=1) for ilayer in zip(*cat_processes)]

In [89]:
full_alignment = [[torch.zeros(layer_dims, dtype=torch.float, device='cpu')
                    for proc in range(n_processes)]
                    for layer_dims in alignment_dims]
[torch.cat(layer, axis=1).shape for layer in full_alignment]


[torch.Size([1, 9, 1]),
 torch.Size([1, 9, 1]),
 torch.Size([1, 9, 5]),
 torch.Size([1, 9, 10])]

In [116]:
[layer.shape for layer in tmp2]

[torch.Size([1, 36, 1]),
 torch.Size([1, 36, 1]),
 torch.Size([1, 36, 5]),
 torch.Size([1, 36, 10])]

In [122]:
tmp2[0][0, :, :].shape

torch.Size([36, 1])

In [123]:
[layer.shape for layer in tmp2]

n_processes = 3

split_interval = [len(layer[1]) // n_processes for layer in cat_processes]
print(split_interval)
split_list = [[layer[0, :, :][int(i):int(i+split_interval)] for i in torch.arange(len(layer))[::layer_split]] for layer, layer_split in zip(tmp2, split_interval)]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [107]:
tmp = torch.arange(36)
n_processes = 3

split_interval = len(tmp) // n_processes
split_list = [tmp[int(i):int(i+split_interval)] for i in torch.arange(len(tmp))[::split_interval]]

In [108]:
permuted_list = [torch.tensor(pair) for pair in zip(*split_list)]

In [109]:
permuted_list

[tensor([ 0, 12, 24]),
 tensor([ 1, 13, 25]),
 tensor([ 2, 14, 26]),
 tensor([ 3, 15, 27]),
 tensor([ 4, 16, 28]),
 tensor([ 5, 17, 29]),
 tensor([ 6, 18, 30]),
 tensor([ 7, 19, 31]),
 tensor([ 8, 20, 32]),
 tensor([ 9, 21, 33]),
 tensor([10, 22, 34]),
 tensor([11, 23, 35])]

In [70]:
[[torch.cat(layer) for layer in step] for step in cat_processes]

TypeError: cat(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

In [32]:
full_alignment[0].shape

AttributeError: 'list' object has no attribute 'shape'

In [31]:
torch.cat(full_alignment[2]).shape

torch.Size([6, 3, 5])

In [28]:
[torch.cat(layer, dim=1) for layer in full_alignment]

[tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],
 
         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]),
 tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],
 
         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
       

In [ ]:
(n_layers, n_proc, layer_dims)